# Generated by Django 5.2 on 2025-04-16 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_task_deadline_alter_task_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admins',
            field=models.ManyToManyField(related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
